/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Again: typeof import('./src/pages/Again.vue')['default']
    Appeareance: typeof import('./src/pages/Appeareance.vue')['default']
    BackProfilePage: typeof import('./src/layouts/BackProfilePage.vue')['default']
    Board: typeof import('./src/pages/Board.vue')['default']
    Button: typeof import('primevue/button')['default']
    Controls: typeof import('./src/pages/Controls.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Index: typeof import('./src/pages/Index.vue')['default']
    Internet: typeof import('./src/pages/multiplayer/Internet.vue')['default']
    Language: typeof import('./src/pages/Language.vue')['default']
    Local: typeof import('./src/pages/multiplayer/Local.vue')['default']
    Locale: typeof import('./src/components/Locale.vue')['default']
    Main: typeof import('./src/pages/Main.vue')['default']
    MenuBackLayout: typeof import('./src/layouts/MenuBackLayout.vue')['default']
    MenuButton: typeof import('./src/components/MenuButton.vue')['default']
    Multiplayer: typeof import('./src/pages/multiplayer/Multiplayer.vue')['default']
    MultiplayerBoard: typeof import('./src/pages/multiplayer/MultiplayerBoard.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    ProfilePage: typeof import('./src/pages/ProfilePage.vue')['default']
    ProfileStatsPanel: typeof import('./src/components/ProfileStatsPanel.vue')['default']
    Room: typeof import('./src/pages/multiplayer/Room.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectKeyCode: typeof import('./src/components/SelectKeyCode.vue')['default']
    Settings: typeof import('./src/pages/Settings.vue')['default']
    Singleplayer: typeof import('./src/pages/Singleplayer.vue')['default']
    Stat: typeof import('./src/components/Stat.vue')['default']
    Stats: typeof import('./src/pages/Stats.vue')['default']
    Summary: typeof import('./src/pages/Summary.vue')['default']
    Theme: typeof import('./src/components/Theme.vue')['default']
    TimeMark: typeof import('./src/components/TimeMark.vue')['default']
    ValueSelect: typeof import('./src/components/ValueSelect.vue')['default']
  }
}
